export interface RouteMetadata {
  title: string;
  description: string;
  canonical: string;
  robots: string;
  ogType?: string;
  schemaType?: string[];
}

export const SITE_URL = 'https://makecontactsheet.com';

export const METADATA_REGISTRY: Record<string, RouteMetadata> = {
  '/': {
    title: 'Contact Sheet Maker — Free Online Photo Proof Sheets',
    description: 'Make contact sheets, photo collages, and mood boards free in your browser. Keep filenames, review selects, and export 300 DPI print-ready PDFs.',
    canonical: `${SITE_URL}/`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['WebSite', 'Organization', 'SoftwareApplication'],
  },
  '/auto-cull-photos': {
    title: 'Auto-Cull Blurry Photos — Free AI Sharpness Filter',
    description: 'Automatically cull blurry and out-of-focus photos with local AI sharpness scoring. Runs in your browser with zero uploads.',
    canonical: `${SITE_URL}/auto-cull-photos`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'HowTo', 'BreadcrumbList'],
  },
  '/batch-photo-tools': {
    title: 'Batch Photo Editor — Rename, Convert & Extract EXIF',
    description: 'Free batch photo editing tools: rename files with tokens, extract EXIF data, and convert image formats locally. No uploads or installs required.',
    canonical: `${SITE_URL}/batch-photo-tools`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'BreadcrumbList'],
  },
  '/photo-contact-sheet-maker': {
    title: 'Photo Contact Sheet — Free Proof Sheet Generator',
    description: 'Generate photo contact sheets online with camera filenames, custom grids, and 300 DPI PDF exports. Free, private, and runs in your browser.',
    canonical: `${SITE_URL}/photo-contact-sheet-maker`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'BreadcrumbList'],
  },
  '/bulk-resize-photos-to-16-9': {
    title: 'Bulk Resize Photos to 16:9 — Free Batch Cropper',
    description: 'Crop and resize photos to 16:9 widescreen in bulk. Private in-browser processing with adjustable quality. No uploads needed.',
    canonical: `${SITE_URL}/bulk-resize-photos-to-16-9`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'HowTo', 'BreadcrumbList'],
  },
  '/compress-photos-for-web': {
    title: 'Compress Photos for Web — Free JPEG, WebP & PNG Tool',
    description: 'Compress photos for websites and social media in your browser. Reduce file size without quality loss. No server uploads, 100% private.',
    canonical: `${SITE_URL}/compress-photos-for-web`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'HowTo', 'BreadcrumbList'],
  },
  // Indexable in its own right: the route carries a full copy block under the
  // app (how it works, every configuration field, shortcuts, formats, FAQ), so
  // it self-canonicalises and sits in the sitemap. Its target phrasing is
  // deliberately the *editor / full screen* wording rather than
  // "photo contact sheet maker", which `/photo-contact-sheet-maker` owns — two
  // pages chasing one phrase split their own signals.
  '/studio/contact-sheet': {
    title: 'Contact Sheet Editor — Full-Screen Photo Studio',
    description: 'Full-screen contact sheet editor with custom grids, camera filenames, keyboard review shortcuts, and print-ready PDF exports. Runs locally.',
    canonical: `${SITE_URL}/studio/contact-sheet`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'BreadcrumbList'],
  },
  '/photo-collage-maker': {
    title: 'Photo Collage Maker — Free Online Grid & Story Layouts',
    description: 'Create photo collages online for free. Pick from grid, story, and comparison layouts. Export high-res images with zero cloud uploads.',
    canonical: `${SITE_URL}/photo-collage-maker`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'BreadcrumbList'],
  },
  '/mood-board-maker': {
    title: 'Mood Board Maker — Free Online Visual Direction Studio',
    description: 'Design mood boards and lookbooks for free on a freeform canvas. Drag photos, add color swatches and notes, then export at 300 DPI.',
    canonical: `${SITE_URL}/mood-board-maker`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'BreadcrumbList'],
  },
  '/mood-board-templates': {
    title: 'Mood Board Templates — Free Aesthetic Presets & Layouts',
    description: 'Browse free mood board templates for photography, fashion, and branding. Pick editorial, lookbook, or minimal presets and customize instantly.',
    canonical: `${SITE_URL}/mood-board-templates`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['BreadcrumbList'],
  },
  '/contact-sheet-template': {
    title: 'Contact Sheet Templates — Free Printable Proof Layouts',
    description: 'Free printable contact sheet templates in A4, US Letter, and 16:9 formats. Calibrated grids with filenames and 300 DPI export support.',
    canonical: `${SITE_URL}/contact-sheet-template`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['BreadcrumbList'],
  },
  '/collage-templates': {
    title: 'Photo Collage Templates — Free Creative Grid Layouts',
    description: 'Explore free photo collage templates with hero, triptych, and social media grid layouts. Customize and export directly in your browser.',
    canonical: `${SITE_URL}/collage-templates`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['BreadcrumbList'],
  },
  '/guides/how-to-make-a-contact-sheet': {
    title: 'How to Make a Contact Sheet — Step-by-Step Guide',
    description: 'Learn how to make a contact sheet with free tools, Photoshop, or Lightroom. Step-by-step photo proof sheet tutorial with printable examples.',
    canonical: `${SITE_URL}/guides/how-to-make-a-contact-sheet`,
    robots: 'index, follow',
    ogType: 'article',
    schemaType: ['HowTo', 'BreadcrumbList'],
  },
  '/guides/how-to-make-photo-collage': {
    title: 'How to Make a Photo Collage Online — Easy Tutorial',
    description: 'Step-by-step tutorial to make a photo collage online for free. Combine pictures into balanced grid layouts in minutes, no software needed.',
    canonical: `${SITE_URL}/guides/how-to-make-photo-collage`,
    robots: 'index, follow',
    ogType: 'article',
    schemaType: ['HowTo', 'BreadcrumbList'],
  },
  '/guides/how-to-make-a-mood-board': {
    title: 'How to Make a Mood Board — Step-by-Step Guide',
    description: 'Step-by-step mood board tutorial for photoshoots, brand books, and lookbooks. Learn composition, color swatches, and 300 DPI print exports.',
    canonical: `${SITE_URL}/guides/how-to-make-a-mood-board`,
    robots: 'index, follow',
    ogType: 'article',
    schemaType: ['HowTo', 'BreadcrumbList'],
  },
  '/guides/photo-proof-sheet-with-filenames': {
    title: 'Photo Proof Sheet with Filenames — Workflow Guide',
    description: 'Create a photo proof sheet with camera filenames preserved. Simplify client selection and streamline your Lightroom culling workflow.',
    canonical: `${SITE_URL}/guides/photo-proof-sheet-with-filenames`,
    robots: 'index, follow',
    ogType: 'article',
    schemaType: ['HowTo', 'BreadcrumbList'],
  },
  '/guides/standard-large-photo-frames-and-print-sizes': {
    title: 'Large Photo Frames & Print Sizes Guide — Dimensions & Math',
    description: 'Complete guide to large photo frames and print sizes (11x14 to 24x36). Learn aspect ratios, matting math, DPI formulas, and gallery hanging rules.',
    canonical: `${SITE_URL}/guides/standard-large-photo-frames-and-print-sizes`,
    robots: 'index, follow',
    ogType: 'article',
    schemaType: ['HowTo', 'BreadcrumbList'],
  },
  '/guides/wedding-photography-proofing-workflow': {
    title: 'Wedding Photography Proofing Workflow — Client Selects Guide',
    description: 'Streamline your wedding photography proofing and culling workflow. Learn 3-pass culling, filename-backed proof sheets, and Lightroom XMP selection sync.',
    canonical: `${SITE_URL}/guides/wedding-photography-proofing-workflow`,
    robots: 'index, follow',
    ogType: 'article',
    schemaType: ['HowTo', 'BreadcrumbList'],
  },
  '/guides/large-photo-albums-vs-proof-books': {
    title: 'Large Photo Albums vs Proof Books — Photography Guide',
    description: 'Compare large photo albums and proof books for client delivery. Learn printing costs, gutter margin safety, layout geometry, and proofing options.',
    canonical: `${SITE_URL}/guides/large-photo-albums-vs-proof-books`,
    robots: 'index, follow',
    ogType: 'article',
    schemaType: ['HowTo', 'BreadcrumbList'],
  },
  '/compare/photoshop-contact-sheet-alternative': {
    title: 'Photoshop Contact Sheet Alternative — Faster Proofing',
    description: 'Compare Make Contact Sheet to Adobe Photoshop for creating proof sheets. Faster grid setup, live preview, and no Creative Cloud subscription.',
    canonical: `${SITE_URL}/compare/photoshop-contact-sheet-alternative`,
    robots: 'index, follow',
    ogType: 'article',
    schemaType: ['BreadcrumbList'],
  },
  '/about-us': {
    title: 'About Us — Make Contact Sheet',
    description: 'Meet the team behind Make Contact Sheet, the free browser-first workspace for photo proof sheets, collages, and client review tools.',
    canonical: `${SITE_URL}/about-us`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['Organization', 'BreadcrumbList'],
  },
  '/contact-us': {
    title: 'Contact Us — Make Contact Sheet',
    description: 'Get in touch with the Make Contact Sheet team for support, feedback, or partnership inquiries about our photo workspace tools.',
    canonical: `${SITE_URL}/contact-us`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['BreadcrumbList'],
  },
  '/privacy-policy': {
    title: 'Privacy Policy — Make Contact Sheet',
    description: 'Make Contact Sheet privacy policy. All image processing runs locally in your browser. No photos are uploaded to external servers.',
    canonical: `${SITE_URL}/privacy-policy`,
    robots: 'noindex, follow',
    ogType: 'website',
    schemaType: ['BreadcrumbList'],
  },
  '/terms-and-conditions': {
    title: 'Terms and Conditions — Make Contact Sheet',
    description: 'Terms and conditions for using the Make Contact Sheet online photo workspace, including contact sheet, collage, and review tools.',
    canonical: `${SITE_URL}/terms-and-conditions`,
    robots: 'noindex, follow',
    ogType: 'website',
    schemaType: ['BreadcrumbList'],
  },
  '/free-8x10-photo-prints': {
    title: '8×10 Photo Print Saver — Free Multi-Photo Layout Tool',
    description: 'Fit multiple photos on an 8×10 print for cheap drugstore printing. Combine 5×7s, 4×5s, or wallets at 300 DPI. Free and private.',
    canonical: `${SITE_URL}/free-8x10-photo-prints`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'HowTo', 'BreadcrumbList'],
  },
  '/large-photo-prints': {
    title: 'Large Photo Prints — Free 16×20 & 24×36 Layout Maker',
    description: 'Create large photo print layouts for 11×14, 16×20, and 24×36 posters at 300 DPI. Arrange photos into gang sheets for affordable printing.',
    canonical: `${SITE_URL}/large-photo-prints`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'HowTo', 'BreadcrumbList'],
  },
  '/lightroom-client-selection-workflow': {
    title: 'Lightroom Client Selection Workflow — XMP Sync Guide',
    description: 'Sync client photo selections into Lightroom Classic with XMP sidecar files. Step-by-step guide for photographers, no plugins needed.',
    canonical: `${SITE_URL}/lightroom-client-selection-workflow`,
    robots: 'index, follow',
    ogType: 'article',
    schemaType: ['HowTo', 'SoftwareApplication', 'BreadcrumbList'],
  },
  '/white-label-client-gallery': {
    title: 'White-Label Client Photo Gallery — Free Proofing Portal',
    description: 'Build branded client photo proofing portals with your studio logo and colors. No monthly fees, no cloud limits, and 100% private.',
    canonical: `${SITE_URL}/white-label-client-gallery`,
    robots: 'index, follow',
    ogType: 'website',
    schemaType: ['SoftwareApplication', 'BreadcrumbList'],
  },
  '/404': {
    title: 'Page Not Found — Make Contact Sheet',
    description: 'The page you requested could not be found. Return to Make Contact Sheet to create contact sheets, photo collages, or mood boards for free.',
    canonical: `${SITE_URL}/404`,
    robots: 'noindex, follow',
    ogType: 'website',
  },
};
