import type { CollageTemplate, LayoutConfig } from '../types';

export interface ContactSheetPreset {
  id: string;
  name: string;
  description: string;
  category: 'standard' | 'digital' | 'client';
  config: Partial<LayoutConfig>;
}

export const CONTACT_SHEET_PRESETS: ContactSheetPreset[] = [
  {
    id: 'a4-portrait-proof',
    name: 'A4 Portrait Proof Sheet',
    description: 'Standard print review format (4×5 grid, 20 photos per page)',
    category: 'standard',
    config: {
      pageSize: 'a4',
      orientation: 'portrait',
      columns: 4,
      rows: 5,
      spacing: 12,
      margin: 24,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
  {
    id: 'a4-landscape-proof',
    name: 'A4 Landscape Proof Sheet',
    description: 'Wide-format horizontal print review (5×4 grid)',
    category: 'standard',
    config: {
      pageSize: 'a4',
      orientation: 'landscape',
      columns: 5,
      rows: 4,
      spacing: 12,
      margin: 24,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
  {
    id: 'us-letter-portrait',
    name: 'US Letter Portrait Proof',
    description: 'North American standard print review sheet',
    category: 'standard',
    config: {
      pageSize: 'letter',
      orientation: 'portrait',
      columns: 4,
      rows: 5,
      spacing: 12,
      margin: 24,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
  {
    id: 'us-letter-landscape',
    name: 'US Letter Landscape Proof',
    description: 'North American wide format review sheet',
    category: 'standard',
    config: {
      pageSize: 'letter',
      orientation: 'landscape',
      columns: 5,
      rows: 4,
      spacing: 12,
      margin: 24,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
  {
    id: '16-9-digital-board',
    name: '16:9 Digital Review Board',
    description: 'Screen-optimized 1080p/4K presentation layout (4×3 grid)',
    category: 'digital',
    config: {
      pageSize: '16-9',
      orientation: 'landscape',
      columns: 4,
      rows: 3,
      spacing: 16,
      margin: 32,
      fit: 'contain',
      showLabels: true,
      labelType: 'both',
      labelPosition: 'below',
    },
  },
  {
    id: 'client-selection-sheet',
    name: 'Client Selection Sheet',
    description: 'Large photos (3×4 grid) with index numbers and status indicators',
    category: 'client',
    config: {
      pageSize: 'a4',
      orientation: 'portrait',
      columns: 3,
      rows: 4,
      spacing: 16,
      margin: 28,
      fit: 'contain',
      showLabels: true,
      labelType: 'both',
      labelPosition: 'below',
      showStatusBadges: true,
    },
  },
  {
    id: 'filename-first-proof',
    name: 'Filename-First Proof Sheet',
    description: 'Dense 4×6 grid maximizing thumbnail count and label legibility',
    category: 'client',
    config: {
      pageSize: 'letter',
      orientation: 'portrait',
      columns: 4,
      rows: 6,
      spacing: 10,
      margin: 20,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
];

export const COLLAGE_TEMPLATES: CollageTemplate[] = [
  {
    id: 'side-by-side-2',
    name: 'Side-by-Side (2 Photos)',
    description: 'Clean horizontal comparison or dual portrait presentation',
    category: 'basic',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 1, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.5, h: 1, fit: 'cover' },
    ],
  },
  {
    id: 'three-strip-h',
    name: 'Three-Photo Strip',
    description: 'Horizontal triptych storytelling layout',
    category: 'basic',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1 / 3, h: 1, fit: 'cover' },
      { x: 1 / 3, y: 0, w: 1 / 3, h: 1, fit: 'cover' },
      { x: 2 / 3, y: 0, w: 1 / 3, h: 1, fit: 'cover' },
    ],
  },
  {
    id: 'three-hero-split',
    name: 'Hero + 2 Stacked',
    description: 'One prominent hero shot on left, 2 detail shots on right',
    category: 'showcase',
    aspectRatio: 4 / 3,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.6, h: 1, fit: 'cover' },
      { x: 0.6, y: 0, w: 0.4, h: 0.5, fit: 'cover' },
      { x: 0.6, y: 0.5, w: 0.4, h: 0.5, fit: 'cover' },
    ],
  },
  {
    id: 'grid-2x2',
    name: '2×2 Square Grid',
    description: 'Classic balanced 4-photo square grid',
    category: 'basic',
    aspectRatio: 1,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 0.5, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.5, h: 0.5, fit: 'cover' },
      { x: 0, y: 0.5, w: 0.5, h: 0.5, fit: 'cover' },
      { x: 0.5, y: 0.5, w: 0.5, h: 0.5, fit: 'cover' },
    ],
  },
  {
    id: 'grid-3x3',
    name: '3×3 Square Grid',
    description: '9-photo moodboard and Instagram gallery showcase',
    category: 'basic',
    aspectRatio: 1,
    defaultSpacing: 10,
    defaultMargin: 14,
    cells: [
      { x: 0, y: 0, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 1/3, y: 0, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 2/3, y: 0, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 0, y: 1/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 1/3, y: 1/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 2/3, y: 1/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 0, y: 2/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 1/3, y: 2/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 2/3, y: 2/3, w: 1/3, h: 1/3, fit: 'cover' },
    ],
  },
  {
    id: 'social-portrait-4-5',
    name: 'Social Portrait (4:5)',
    description: '1 top landscape photo + 2 bottom vertical portrait tiles',
    category: 'social',
    aspectRatio: 4 / 5,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1, h: 0.55, fit: 'cover' },
      { x: 0, y: 0.55, w: 0.5, h: 0.45, fit: 'cover' },
      { x: 0.5, y: 0.55, w: 0.5, h: 0.45, fit: 'cover' },
    ],
  },
  {
    id: 'social-story-9-16',
    name: 'Social Story (9:16)',
    description: 'Vertical mobile story with hero header and dual footer frames',
    category: 'social',
    aspectRatio: 9 / 16,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1, h: 0.6, fit: 'cover' },
      { x: 0, y: 0.6, w: 0.5, h: 0.4, fit: 'cover' },
      { x: 0.5, y: 0.6, w: 0.5, h: 0.4, fit: 'cover' },
    ],
  },
  {
    id: 'before-after',
    name: 'Before & After Comparison',
    description: 'Split presentation labeled for photo retouching & edits',
    category: 'comparison',
    aspectRatio: 16 / 9,
    defaultSpacing: 8,
    defaultMargin: 12,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 1, fit: 'contain' },
      { x: 0.5, y: 0, w: 0.5, h: 1, fit: 'contain' },
    ],
  },
  {
    id: 'portfolio-wall',
    name: 'Portfolio Mosaic Wall',
    description: 'Dynamic 5-photo asymmetrical architectural collage',
    category: 'showcase',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 1, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.25, h: 0.5, fit: 'cover' },
      { x: 0.75, y: 0, w: 0.25, h: 0.5, fit: 'cover' },
      { x: 0.5, y: 0.5, w: 0.5, h: 0.5, fit: 'cover' },
    ],
  },
];
