import type { CollageTemplate, LayoutConfig } from '../types';

export type ContactSheetCategory = 'standard' | 'film' | 'client' | 'digital';

export interface ContactSheetPreset {
  id: string;
  name: string;
  description: string;
  category: ContactSheetCategory;
  config: Partial<LayoutConfig>;
}

/** Human labels for the sidebar group headings, in display order. */
export const CONTACT_SHEET_CATEGORY_LABELS: Record<ContactSheetCategory, string> = {
  standard: 'Print standards',
  film: 'Film & index sheets',
  client: 'Client review',
  digital: 'Screen & social',
};

/**
 * Structural fields a preset is responsible for. Applied underneath the
 * preset's own config so switching from a preset that turns on a title band to
 * one that doesn't actually turns the band back off, instead of leaving it on
 * from the previous choice.
 *
 * `bg` / `textColor` are deliberately absent: those are a taste choice the user
 * makes once, and a preset should only override them when it explicitly says so
 * (as the white gallery sheet does).
 */
export const PRESET_STRUCTURAL_BASE: Partial<LayoutConfig> = {
  fit: 'contain',
  showLabels: true,
  labelType: 'filename',
  labelPosition: 'below',
  fontSize: 11,
  showStatusBadges: false,
  showHeader: false,
  headerText: '',
  showPageNumbers: false,
  cellBorderWidth: 0,
  cellRadius: 0,
  fillOrder: 'row',
  labelUppercase: false,
  labelHideExtension: false,
  labelAlign: 'center',
  showWatermark: false,
  watermarkType: 'text',
  watermarkText: 'PROOF',
  watermarkStyle: 'diagonal',
  watermarkOpacity: 20,
  watermarkColor: '#ffffff',
  watermarkImageUrl: '',
  watermarkImageScale: 30,
  watermarkImagePosition: 'bottom-right',
  showExifOverlay: false,
  exifTokenTemplate: '{basename} · {focal} {fstop} {shutter} ISO {iso}',
  exifBadgeStyle: 'plain-text',
};

export const CONTACT_SHEET_PRESETS: ContactSheetPreset[] = [
  {
    id: 'a4-portrait-proof',
    name: 'A4 Portrait Proof Sheet',
    description: 'Standard print review format (4×5 grid, 20 photos per page)',
    category: 'standard',
    config: {
      pageSize: 'a4',
      orientation: 'portrait',
      columns: 4,
      rows: 5,
      spacing: 12,
      margin: 24,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
  {
    id: 'a4-landscape-proof',
    name: 'A4 Landscape Proof Sheet',
    description: 'Wide-format horizontal print review (5×4 grid)',
    category: 'standard',
    config: {
      pageSize: 'a4',
      orientation: 'landscape',
      columns: 5,
      rows: 4,
      spacing: 12,
      margin: 24,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
  {
    id: 'us-letter-portrait',
    name: 'US Letter Portrait Proof',
    description: 'North American standard print review sheet',
    category: 'standard',
    config: {
      pageSize: 'letter',
      orientation: 'portrait',
      columns: 4,
      rows: 5,
      spacing: 12,
      margin: 24,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
  {
    id: 'us-letter-landscape',
    name: 'US Letter Landscape Proof',
    description: 'North American wide format review sheet',
    category: 'standard',
    config: {
      pageSize: 'letter',
      orientation: 'landscape',
      columns: 5,
      rows: 4,
      spacing: 12,
      margin: 24,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
  {
    id: '16-9-digital-board',
    name: '16:9 Digital Review Board',
    description: 'Screen-optimized 1080p/4K presentation layout (4×3 grid)',
    category: 'digital',
    config: {
      pageSize: '16-9',
      orientation: 'landscape',
      columns: 4,
      rows: 3,
      spacing: 16,
      margin: 32,
      fit: 'contain',
      showLabels: true,
      labelType: 'both',
      labelPosition: 'below',
    },
  },
  {
    id: 'client-selection-sheet',
    name: 'Client Selection Sheet',
    description: 'Large photos (3×4 grid) with index numbers and status indicators',
    category: 'client',
    config: {
      pageSize: 'a4',
      orientation: 'portrait',
      columns: 3,
      rows: 4,
      spacing: 16,
      margin: 28,
      fit: 'contain',
      showLabels: true,
      labelType: 'both',
      labelPosition: 'below',
      showStatusBadges: true,
    },
  },
  {
    id: 'filename-first-proof',
    name: 'Filename-First Proof Sheet',
    description: 'Dense 4×6 grid maximizing thumbnail count and label legibility',
    category: 'client',
    config: {
      pageSize: 'letter',
      orientation: 'portrait',
      columns: 4,
      rows: 6,
      spacing: 10,
      margin: 20,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
    },
  },
  {
    id: 'gallery-white-print',
    name: 'Gallery White Print Sheet',
    description: 'White paper, hairline keylines, titled band — for printing and filing',
    category: 'standard',
    config: {
      pageSize: 'a4',
      orientation: 'portrait',
      columns: 3,
      rows: 4,
      spacing: 18,
      margin: 36,
      fit: 'contain',
      bg: '#ffffff',
      textColor: '#2a1a12',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
      cellBorderWidth: 1,
      cellBorderColor: '#e0d3c4',
      showHeader: true,
      showPageNumbers: true,
    },
  },
  {
    id: 'film-strip-index',
    name: '35mm Strip Index',
    description: 'Very dense 5×7 index in frame order, numbers only — the darkroom proof habit',
    category: 'film',
    config: {
      pageSize: 'letter',
      orientation: 'portrait',
      columns: 5,
      rows: 7,
      spacing: 4,
      margin: 16,
      fit: 'cover',
      showLabels: true,
      labelType: 'number',
      labelPosition: 'below',
      fontSize: 8,
      showPageNumbers: true,
    },
  },
  {
    id: 'square-6x6-proof',
    name: 'Square 6×6 Proof',
    description: 'Square page, 4×4 cropped frames — medium-format and square-crop work',
    category: 'film',
    config: {
      pageSize: 'square',
      orientation: 'portrait',
      columns: 4,
      rows: 4,
      spacing: 10,
      margin: 24,
      fit: 'cover',
      showLabels: true,
      labelType: 'number',
      labelPosition: 'below',
      fontSize: 10,
    },
  },
  {
    id: 'dense-thumbnail-index',
    name: 'Full Shoot Index',
    description: '6×8 = 48 frames per page. Fits a whole card on one or two sheets',
    category: 'film',
    config: {
      pageSize: 'a4',
      orientation: 'portrait',
      columns: 6,
      rows: 8,
      spacing: 4,
      margin: 14,
      fit: 'cover',
      showLabels: true,
      labelType: 'number',
      labelPosition: 'below',
      fontSize: 7,
      showHeader: true,
      showPageNumbers: true,
    },
  },
  {
    id: 'wedding-client-proof',
    name: 'Client Proof — Titled',
    description: '4×3 landscape with a titled band, page numbers and keep/reject marks',
    category: 'client',
    config: {
      pageSize: 'a4',
      orientation: 'landscape',
      columns: 4,
      rows: 3,
      spacing: 18,
      margin: 32,
      fit: 'contain',
      showLabels: true,
      labelType: 'both',
      labelPosition: 'below',
      fontSize: 12,
      showStatusBadges: true,
      showHeader: true,
      showPageNumbers: true,
    },
  },
  {
    id: 'casting-sheet',
    name: 'Casting / Talent Sheet',
    description: '3×3 large frames with the name printed inside the photo',
    category: 'client',
    config: {
      pageSize: 'a4',
      orientation: 'portrait',
      columns: 3,
      rows: 3,
      spacing: 14,
      margin: 28,
      fit: 'cover',
      showLabels: true,
      labelType: 'both',
      labelPosition: 'overlay',
      fontSize: 13,
      showHeader: true,
      cellBorderWidth: 1,
      cellBorderColor: '#4a352b',
    },
  },
  {
    id: 'instagram-grid-preview',
    name: 'Instagram Grid Preview',
    description: 'Square 3×3 of cropped frames, no labels — check a feed before posting',
    category: 'digital',
    config: {
      pageSize: 'square',
      orientation: 'portrait',
      columns: 3,
      rows: 3,
      spacing: 6,
      margin: 6,
      fit: 'cover',
      showLabels: false,
      labelType: 'none',
      labelPosition: 'none',
    },
  },
  {
    id: 'storyboard-6up',
    name: 'Storyboard 6-Up',
    description: '3×2 landscape with numbered panels and a titled band',
    category: 'digital',
    config: {
      pageSize: '16-9',
      orientation: 'landscape',
      columns: 3,
      rows: 2,
      spacing: 20,
      margin: 36,
      fit: 'cover',
      showLabels: true,
      labelType: 'number',
      labelPosition: 'overlay',
      fontSize: 16,
      showHeader: true,
      showPageNumbers: true,
    },
  },
  {
    id: 'studio-tech-exif',
    name: 'Studio Technical EXIF Sheet',
    description: '3×3 large frames with live camera, lens, aperture, shutter and ISO metadata badges',
    category: 'client',
    config: {
      pageSize: 'a4',
      orientation: 'landscape',
      columns: 3,
      rows: 3,
      spacing: 16,
      margin: 24,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
      showExifOverlay: true,
      exifTokenTemplate: '{focal} {fstop} · 1/{shutter}s · ISO {iso}',
      exifBadgeStyle: 'dark-pill',
      showHeader: true,
      showPageNumbers: true,
    },
  },
  {
    id: 'medium-format-6x7',
    name: '120 Film 6×7 Proof (10-Up)',
    description: '2×5 vertical frames matching a full 10-exposure 120 roll film contact print',
    category: 'film',
    config: {
      pageSize: 'a4',
      orientation: 'portrait',
      columns: 2,
      rows: 5,
      spacing: 12,
      margin: 20,
      fit: 'cover',
      bg: '#141210',
      textColor: '#e6ded4',
      showLabels: true,
      labelType: 'number',
      labelPosition: 'below',
      fontSize: 11,
      cellBorderWidth: 1,
      cellBorderColor: '#2e2722',
      showHeader: true,
      showPageNumbers: true,
    },
  },
  {
    id: 'detail-macro-8up',
    name: 'Detail & Focus QC (8-Up)',
    description: '4×2 widescreen frames on clean white paper for evaluating focus and texture sharpness',
    category: 'standard',
    config: {
      pageSize: 'a4',
      orientation: 'landscape',
      columns: 4,
      rows: 2,
      spacing: 20,
      margin: 28,
      fit: 'contain',
      bg: '#ffffff',
      textColor: '#1c1917',
      showLabels: true,
      labelType: 'both',
      labelPosition: 'below',
      cellBorderWidth: 1,
      cellBorderColor: '#e5e0d8',
      showHeader: true,
      showPageNumbers: true,
    },
  },
  {
    id: 'lookbook-spread-2up',
    name: 'Lookbook Double Spread (2-Up)',
    description: 'Two extra-large presentation frames side-by-side with generous gallery margins',
    category: 'standard',
    config: {
      pageSize: 'a4',
      orientation: 'landscape',
      columns: 2,
      rows: 1,
      spacing: 28,
      margin: 40,
      fit: 'contain',
      showLabels: true,
      labelType: 'filename',
      labelPosition: 'below',
      fontSize: 13,
      showHeader: false,
      showPageNumbers: true,
    },
  },
  {
    id: 'social-storyboard-8up',
    name: 'Reel & Short Storyboard (8-Up)',
    description: '4×2 screen presentation board with numbered cards for vertical video pacing',
    category: 'digital',
    config: {
      pageSize: '16-9',
      orientation: 'landscape',
      columns: 4,
      rows: 2,
      spacing: 16,
      margin: 28,
      fit: 'contain',
      showLabels: true,
      labelType: 'both',
      labelPosition: 'below',
      fontSize: 12,
      showStatusBadges: true,
      showHeader: true,
      showPageNumbers: true,
    },
  },
  {
    id: 'archival-mega-index-70',
    name: 'Archival Lab Mega Index (70-Up)',
    description: '7×10 dense frame index fitting two complete 36-exposure rolls on a single sheet',
    category: 'film',
    config: {
      pageSize: 'a4',
      orientation: 'portrait',
      columns: 7,
      rows: 10,
      spacing: 3,
      margin: 12,
      fit: 'cover',
      showLabels: true,
      labelType: 'number',
      labelPosition: 'below',
      fontSize: 6,
      showHeader: true,
      showPageNumbers: true,
    },
  },
  {
    id: 'print-8x10-2up-5x7',
    name: 'Two 5×7s on 8×10 Sheet (Print Saver)',
    description: 'Save money by printing two 5×7 photos on a single 8×10 sheet at the pharmacy or lab',
    category: 'standard',
    config: {
      pageSize: '8x10',
      orientation: 'portrait',
      columns: 1,
      rows: 2,
      spacing: 10,
      margin: 10,
      fit: 'cover',
      showLabels: false,
    },
  },
  {
    id: 'print-8x10-4up-4x5',
    name: 'Four 4×5s on 8×10 Sheet (Print Saver)',
    description: 'Print four 4×5 photos perfectly on one 8×10 sheet',
    category: 'standard',
    config: {
      pageSize: '8x10',
      orientation: 'portrait',
      columns: 2,
      rows: 2,
      spacing: 10,
      margin: 10,
      fit: 'cover',
      showLabels: false,
    },
  },
  {
    id: 'print-8x10-8up-wallet',
    name: 'Eight Wallet Prints on 8×10',
    description: 'Print eight 2.5×3.5 wallet size photos on a single 8×10 sheet',
    category: 'standard',
    config: {
      pageSize: '8x10',
      orientation: 'portrait',
      columns: 2,
      rows: 4,
      spacing: 10,
      margin: 10,
      fit: 'cover',
      showLabels: false,
    },
  },
  {
    id: 'print-8x10-full',
    name: '8×10 Full Sheet Print',
    description: 'Standard 8×10 print format with optional borders',
    category: 'standard',
    config: {
      pageSize: '8x10',
      orientation: 'portrait',
      columns: 1,
      rows: 1,
      spacing: 0,
      margin: 0,
      fit: 'contain',
      showLabels: false,
    },
  },
  {
    id: 'poster-16x20-gang',
    name: '16×20 Gang Sheet (6-Up)',
    description: 'Six 5×7 prints on a 16×20 poster sheet (2×3 grid) for pharmacy and lab print savings',
    category: 'standard',
    config: {
      pageSize: '16x20',
      orientation: 'portrait',
      columns: 2,
      rows: 3,
      spacing: 10,
      margin: 10,
      fit: 'cover',
      showLabels: false,
    },
  },
  {
    id: 'poster-24x36-gang',
    name: '24×36 Large Poster Gang Sheet (12-Up)',
    description: 'Twelve prints on a 24×36 large poster (3×4 grid) for high-efficiency batch printing',
    category: 'standard',
    config: {
      pageSize: '24x36',
      orientation: 'portrait',
      columns: 3,
      rows: 4,
      spacing: 10,
      margin: 10,
      fit: 'cover',
      showLabels: false,
    },
  },
  {
    id: 'print-11x14-4up',
    name: 'Four-Up on 11×14 Sheet (Print Saver)',
    description: 'Four photos on an 11×14 small poster sheet (2×2 grid)',
    category: 'standard',
    config: {
      pageSize: '11x14',
      orientation: 'portrait',
      columns: 2,
      rows: 2,
      spacing: 10,
      margin: 10,
      fit: 'cover',
      showLabels: false,
    },
  },
];

export const COLLAGE_TEMPLATES: CollageTemplate[] = [
  {
    id: 'side-by-side-2',
    name: 'Side-by-Side (2 Photos)',
    description: 'Clean horizontal comparison or dual portrait presentation',
    category: 'basic',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 1, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.5, h: 1, fit: 'cover' },
    ],
  },
  {
    id: 'three-strip-h',
    name: 'Three-Photo Strip',
    description: 'Horizontal triptych storytelling layout',
    category: 'basic',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1 / 3, h: 1, fit: 'cover' },
      { x: 1 / 3, y: 0, w: 1 / 3, h: 1, fit: 'cover' },
      { x: 2 / 3, y: 0, w: 1 / 3, h: 1, fit: 'cover' },
    ],
  },
  {
    id: 'three-strip-v',
    name: 'Vertical Triptych (3 Photos)',
    description: 'Three stacked horizontal panoramic frames for mobile stories and cinematic sequences',
    category: 'social',
    aspectRatio: 9 / 16,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1, h: 1 / 3, fit: 'cover' },
      { x: 0, y: 1 / 3, w: 1, h: 1 / 3, fit: 'cover' },
      { x: 0, y: 2 / 3, w: 1, h: 1 / 3, fit: 'cover' },
    ],
  },
  {
    id: 'film-strip-4',
    name: 'Film Strip Quad (4 Photos)',
    description: 'Four vertical frames side by side in a cinematic 16:9 widescreen strip',
    category: 'basic',
    aspectRatio: 16 / 9,
    defaultSpacing: 10,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.25, h: 1, fit: 'cover' },
      { x: 0.25, y: 0, w: 0.25, h: 1, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.25, h: 1, fit: 'cover' },
      { x: 0.75, y: 0, w: 0.25, h: 1, fit: 'cover' },
    ],
  },
  {
    id: 'three-hero-split',
    name: 'Hero + 2 Stacked',
    description: 'One prominent hero shot on left, 2 detail shots on right',
    category: 'showcase',
    aspectRatio: 4 / 3,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.6, h: 1, fit: 'cover' },
      { x: 0.6, y: 0, w: 0.4, h: 0.5, fit: 'cover' },
      { x: 0.6, y: 0.5, w: 0.4, h: 0.5, fit: 'cover' },
    ],
  },
  {
    id: 'hero-golden-quad',
    name: 'Master Hero + 3 Stacked',
    description: 'One dominant two-thirds hero photo on left, three stacked horizontal detail frames on right',
    category: 'showcase',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 2 / 3, h: 1, fit: 'cover' },
      { x: 2 / 3, y: 0, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 2 / 3, y: 1 / 3, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 2 / 3, y: 2 / 3, w: 1 / 3, h: 1 / 3, fit: 'cover' },
    ],
  },
  {
    id: 'cinematic-split',
    name: 'Cinematic Header + 3 Insets',
    description: 'One wide landscape header across top, three equal detail frames along bottom',
    category: 'showcase',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1, h: 0.62, fit: 'cover' },
      { x: 0, y: 0.62, w: 1 / 3, h: 0.38, fit: 'cover' },
      { x: 1 / 3, y: 0.62, w: 1 / 3, h: 0.38, fit: 'cover' },
      { x: 2 / 3, y: 0.62, w: 1 / 3, h: 0.38, fit: 'cover' },
    ],
  },
  {
    id: 'grid-2x2',
    name: '2×2 Square Grid',
    description: 'Classic balanced 4-photo square grid',
    category: 'basic',
    aspectRatio: 1,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 0.5, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.5, h: 0.5, fit: 'cover' },
      { x: 0, y: 0.5, w: 0.5, h: 0.5, fit: 'cover' },
      { x: 0.5, y: 0.5, w: 0.5, h: 0.5, fit: 'cover' },
    ],
  },
  {
    id: 'grid-3x3',
    name: '3×3 Square Grid',
    description: '9-photo moodboard and Instagram gallery showcase',
    category: 'basic',
    aspectRatio: 1,
    defaultSpacing: 10,
    defaultMargin: 14,
    cells: [
      { x: 0, y: 0, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 1/3, y: 0, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 2/3, y: 0, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 0, y: 1/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 1/3, y: 1/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 2/3, y: 1/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 0, y: 2/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 1/3, y: 2/3, w: 1/3, h: 1/3, fit: 'cover' },
      { x: 2/3, y: 2/3, w: 1/3, h: 1/3, fit: 'cover' },
    ],
  },
  {
    id: 'editorial-mosaic-5',
    name: 'Editorial Center Hero (5 Photos)',
    description: 'Dominant center vertical portrait flanked by two stacked frames on each side',
    category: 'showcase',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.25, h: 0.5, fit: 'cover' },
      { x: 0, y: 0.5, w: 0.25, h: 0.5, fit: 'cover' },
      { x: 0.25, y: 0, w: 0.5, h: 1, fit: 'cover' },
      { x: 0.75, y: 0, w: 0.25, h: 0.5, fit: 'cover' },
      { x: 0.75, y: 0.5, w: 0.25, h: 0.5, fit: 'cover' },
    ],
  },
  {
    id: 'grid-2x3-portrait',
    name: 'Social Portrait 2×3 (6 Photos)',
    description: 'Two columns of three vertical frames calibrated for Instagram 4:5 portrait feeds',
    category: 'social',
    aspectRatio: 4 / 5,
    defaultSpacing: 10,
    defaultMargin: 14,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0, y: 1 / 3, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0.5, y: 1 / 3, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0, y: 2 / 3, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0.5, y: 2 / 3, w: 0.5, h: 1 / 3, fit: 'cover' },
    ],
  },
  {
    id: 'center-hero-cross',
    name: 'Central Spotlight (5 Photos)',
    description: 'Four corner photos framing a prominent center highlight in a square moodboard',
    category: 'showcase',
    aspectRatio: 1,
    defaultSpacing: 10,
    defaultMargin: 14,
    cells: [
      { x: 0, y: 0, w: 0.25, h: 1, fit: 'cover' },
      { x: 0.75, y: 0, w: 0.25, h: 1, fit: 'cover' },
      { x: 0.25, y: 0, w: 0.5, h: 0.25, fit: 'cover' },
      { x: 0.25, y: 0.75, w: 0.5, h: 0.25, fit: 'cover' },
      { x: 0.25, y: 0.25, w: 0.5, h: 0.5, fit: 'cover' },
    ],
  },
  {
    id: 'hero-bottom-grid-5',
    name: 'Panorama + 4 Thumbnails',
    description: 'One panoramic establishing landscape across top, four detail thumbnails below',
    category: 'showcase',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1, h: 0.52, fit: 'cover' },
      { x: 0, y: 0.52, w: 0.25, h: 0.48, fit: 'cover' },
      { x: 0.25, y: 0.52, w: 0.25, h: 0.48, fit: 'cover' },
      { x: 0.5, y: 0.52, w: 0.25, h: 0.48, fit: 'cover' },
      { x: 0.75, y: 0.52, w: 0.25, h: 0.48, fit: 'cover' },
    ],
  },
  {
    id: 'social-portrait-4-5',
    name: 'Social Portrait (4:5)',
    description: '1 top landscape photo + 2 bottom vertical portrait tiles',
    category: 'social',
    aspectRatio: 4 / 5,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1, h: 0.55, fit: 'cover' },
      { x: 0, y: 0.55, w: 0.5, h: 0.45, fit: 'cover' },
      { x: 0.5, y: 0.55, w: 0.5, h: 0.45, fit: 'cover' },
    ],
  },
  {
    id: 'social-story-9-16',
    name: 'Social Story (9:16)',
    description: 'Vertical mobile story with hero header and dual footer frames',
    category: 'social',
    aspectRatio: 9 / 16,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1, h: 0.6, fit: 'cover' },
      { x: 0, y: 0.6, w: 0.5, h: 0.4, fit: 'cover' },
      { x: 0.5, y: 0.6, w: 0.5, h: 0.4, fit: 'cover' },
    ],
  },
  {
    id: 'before-after',
    name: 'Before & After Comparison',
    description: 'Split presentation labeled for photo retouching & edits',
    category: 'comparison',
    aspectRatio: 16 / 9,
    defaultSpacing: 8,
    defaultMargin: 12,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 1, fit: 'contain' },
      { x: 0.5, y: 0, w: 0.5, h: 1, fit: 'contain' },
    ],
  },
  {
    id: 'headline-duo-3-2',
    name: 'Editorial Duo (3:2)',
    description: 'Asymmetrical 55/45 golden duo for portrait and texture pairing with fine art margin',
    category: 'comparison',
    aspectRatio: 3 / 2,
    defaultSpacing: 14,
    defaultMargin: 20,
    cells: [
      { x: 0, y: 0, w: 0.55, h: 1, fit: 'cover' },
      { x: 0.55, y: 0, w: 0.45, h: 1, fit: 'cover' },
    ],
  },
  {
    id: 'portfolio-wall',
    name: 'Portfolio Mosaic Wall',
    description: 'Asymmetrical 4-photo architectural collage: one tall, two small, one wide',
    category: 'showcase',
    aspectRatio: 16 / 9,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 1, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.25, h: 0.5, fit: 'cover' },
      { x: 0.75, y: 0, w: 0.25, h: 0.5, fit: 'cover' },
      { x: 0.5, y: 0.5, w: 0.5, h: 0.5, fit: 'cover' },
    ],
  },
  {
    id: 'collage-8x10-2up-5x7',
    name: 'Two 5x7s on 8x10 (Print Saver)',
    description: 'Two 5x7 stacked/split cells on 8x10',
    category: 'comparison',
    aspectRatio: 0.8,
    defaultSpacing: 10,
    defaultMargin: 10,
    cells: [
      { x: 0, y: 0, w: 1, h: 0.5, fit: 'cover' },
      { x: 0, y: 0.5, w: 1, h: 0.5, fit: 'cover' },
    ],
  },
  {
    id: 'collage-8x10-4up-4x5',
    name: 'Four 4x5s on 8x10 (Print Saver)',
    description: '2x2 grid of 4x5 ratio cells on 8x10',
    category: 'basic',
    aspectRatio: 0.8,
    defaultSpacing: 10,
    defaultMargin: 10,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 0.5, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.5, h: 0.5, fit: 'cover' },
      { x: 0, y: 0.5, w: 0.5, h: 0.5, fit: 'cover' },
      { x: 0.5, y: 0.5, w: 0.5, h: 0.5, fit: 'cover' },
    ],
  },
  {
    id: 'collage-8x10-8up-wallet',
    name: 'Eight Wallet Prints on 8x10',
    description: '2x4 grid of wallet cells on 8x10',
    category: 'basic',
    aspectRatio: 0.8,
    defaultSpacing: 10,
    defaultMargin: 10,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 0.25, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.5, h: 0.25, fit: 'cover' },
      { x: 0, y: 0.25, w: 0.5, h: 0.25, fit: 'cover' },
      { x: 0.5, y: 0.25, w: 0.5, h: 0.25, fit: 'cover' },
      { x: 0, y: 0.5, w: 0.5, h: 0.25, fit: 'cover' },
      { x: 0.5, y: 0.5, w: 0.5, h: 0.25, fit: 'cover' },
      { x: 0, y: 0.75, w: 0.5, h: 0.25, fit: 'cover' },
      { x: 0.5, y: 0.75, w: 0.5, h: 0.25, fit: 'cover' },
    ],
  },
  {
    id: 'poster-16x20-hero-grid',
    name: '16×20 Poster Hero + 4 Insets',
    description: '1 Large 11×14 Hero with 4 stacked detail insets on 16×20 poster format',
    category: 'showcase',
    aspectRatio: 0.8,
    defaultSpacing: 10,
    defaultMargin: 12,
    cells: [
      { x: 0, y: 0, w: 0.65, h: 1, fit: 'cover' },
      { x: 0.65, y: 0, w: 0.35, h: 0.25, fit: 'cover' },
      { x: 0.65, y: 0.25, w: 0.35, h: 0.25, fit: 'cover' },
      { x: 0.65, y: 0.5, w: 0.35, h: 0.25, fit: 'cover' },
      { x: 0.65, y: 0.75, w: 0.35, h: 0.25, fit: 'cover' },
    ],
  },
  {
    id: 'poster-24x36-storyboard',
    name: '24×36 Cinematic Storyboard (9 Photos)',
    description: '9-Photo Cinematic Grid with 3×3 normalized layout calibrated for 24×36 poster prints',
    category: 'showcase',
    aspectRatio: 0.667,
    defaultSpacing: 12,
    defaultMargin: 16,
    cells: [
      { x: 0, y: 0, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 1 / 3, y: 0, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 2 / 3, y: 0, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 0, y: 1 / 3, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 1 / 3, y: 1 / 3, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 2 / 3, y: 1 / 3, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 0, y: 2 / 3, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 1 / 3, y: 2 / 3, w: 1 / 3, h: 1 / 3, fit: 'cover' },
      { x: 2 / 3, y: 2 / 3, w: 1 / 3, h: 1 / 3, fit: 'cover' },
    ],
  },
  {
    id: 'poster-16x20-gang-sheet',
    name: 'Six 5×7s on 16×20 (Gang Sheet)',
    description: '6-Up 5×7 Gang Print Saver on 16×20 poster format',
    category: 'basic',
    aspectRatio: 0.8,
    defaultSpacing: 10,
    defaultMargin: 10,
    cells: [
      { x: 0, y: 0, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0.5, y: 0, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0, y: 1 / 3, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0.5, y: 1 / 3, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0, y: 2 / 3, w: 0.5, h: 1 / 3, fit: 'cover' },
      { x: 0.5, y: 2 / 3, w: 0.5, h: 1 / 3, fit: 'cover' },
    ],
  },
  {
    id: 'poster-24x36-gang-sheet',
    name: 'Twelve-Up on 24×36 (Gang Sheet)',
    description: '12-Up Gang Print Saver on 24×36 large poster format',
    category: 'basic',
    aspectRatio: 0.667,
    defaultSpacing: 10,
    defaultMargin: 10,
    cells: [
      { x: 0, y: 0, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 1 / 3, y: 0, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 2 / 3, y: 0, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 0, y: 0.25, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 1 / 3, y: 0.25, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 2 / 3, y: 0.25, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 0, y: 0.5, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 1 / 3, y: 0.5, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 2 / 3, y: 0.5, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 0, y: 0.75, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 1 / 3, y: 0.75, w: 1 / 3, h: 0.25, fit: 'cover' },
      { x: 2 / 3, y: 0.75, w: 1 / 3, h: 0.25, fit: 'cover' },
    ],
  },
];
